# Generated by Django 5.0.2 on 2024-02-22 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataApp", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("Description", models.TextField()),
                ("image", models.ImageField(blank=True, upload_to="data")),
                ("date", models.DateField()),
                ("by", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="category",
            fields=[
                (
                    "category_name",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="faq",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ques", models.TextField()),
                ("ans", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="initiative",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("image", models.ImageField(blank=True, upload_to="data")),
                ("profile", models.TextField()),
                ("Description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("video", models.FileField(upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="structure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tool_name", models.CharField(max_length=100)),
                ("tool_image", models.ImageField(blank=True, upload_to="data")),
                ("tool_description", models.TextField()),
                ("tool_link", models.URLField(max_length=500)),
                (
                    "category_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="DataApp.category",
                    ),
                ),
            ],
        ),
    ]
