# Generated by Django 5.0.2 on 2024-02-29 06:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataApp", "0002_article_category_faq_initiative_video_structure"),
    ]

    operations = [
        migrations.CreateModel(
            name="contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_Name", models.CharField(max_length=100)),
                ("last_Name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
