# Generated by Django 5.0.2 on 2024-03-02 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataApp", "0003_contact"),
    ]

    operations = [
        migrations.CreateModel(
            name="contactus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("email_id", models.EmailField(max_length=254)),
                ("message", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name="contact",
        ),
    ]
