# Generated by Django 5.0.2 on 2024-03-02 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataApp", "0004_contactus_delete_contact"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="message",
            field=models.CharField(max_length=500),
        ),
    ]
