# Generated by Django 5.0.2 on 2024-03-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataApp", "0005_alter_contactus_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="userregister",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.CharField(max_length=100)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
    ]
