# Generated by Django 5.0.2 on 2024-04-11 09:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataApp", "0007_review"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.TextField()),
                ("message", models.TextField()),
            ],
        ),
    ]
