# Generated by Django 5.0.2 on 2024-04-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataApp", "0008_chatmessage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chatmessage",
            name="user",
            field=models.CharField(max_length=100),
        ),
    ]
