# Generated by Django 5.0.4 on 2024-05-02 09:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("DataApp", "0009_alter_chatmessage_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="initiative",
            old_name="profile",
            new_name="publisher",
        ),
    ]
