# Generated by Django 5.0.4 on 2024-05-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataApp", "0010_rename_profile_initiative_publisher"),
    ]

    operations = [
        migrations.AddField(
            model_name="contactus",
            name="subject",
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
    ]
