# Generated by Django 5.0.4 on 2024-05-03 05:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataApp", "0011_contactus_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="helpsupport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(max_length=100)),
                ("email_id", models.EmailField(max_length=254)),
                ("message", models.CharField(max_length=500)),
            ],
        ),
    ]
