# Generated by Django 5.0.4 on 2024-05-03 05:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("DataApp", "0012_helpsupport"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="helpsupport",
            new_name="helpnsupport",
        ),
    ]
