# Generated by Django 5.0.4 on 2024-05-06 08:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataApp", "0013_rename_helpsupport_helpnsupport"),
    ]

    operations = [
        migrations.AddField(
            model_name="userregister",
            name="Facebook",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userregister",
            name="Github",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userregister",
            name="linkedIn",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userregister",
            name="phone",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
