# Generated by Django 5.0.4 on 2024-05-06 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataApp", "0014_userregister_facebook_userregister_github_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userregister",
            name="dob",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
