# Generated by Django 5.0.4 on 2024-05-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataApp", "0015_userregister_dob"),
    ]

    operations = [
        migrations.AddField(
            model_name="userregister",
            name="image",
            field=models.ImageField(blank=True, upload_to="data"),
        ),
    ]
