# Generated by Django 5.0.4 on 2024-05-07 09:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataApp", "0016_userregister_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(blank=True, upload_to="data"),
        ),
    ]
