# Generated by Django 5.0.4 on 2024-05-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataApp", "0017_category_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="jobsearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jobboards", models.CharField(max_length=100)),
                ("logo", models.ImageField(blank=True, upload_to="data")),
                ("link", models.CharField(max_length=100)),
            ],
        ),
    ]
