# Generated by Django 5.0.4 on 2024-05-14 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataApp", "0018_jobsearch"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobsearch",
            name="review",
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="jobsearch",
            name="reviewername",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
