# Generated by Django 5.0.4 on 2024-05-14 10:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("DataApp", "0019_jobsearch_review_jobsearch_reviewername"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jobsearch",
            name="review",
        ),
        migrations.RemoveField(
            model_name="jobsearch",
            name="reviewername",
        ),
    ]
