# Generated by Django 5.0.4 on 2024-05-14 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("DataApp", "0020_remove_jobsearch_review_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobsearch",
            name="description",
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
